apiVersion: v1
kind: Secret
metadata:
  name: music-db-credentials
  namespace: yeahmusic
stringData:
  POSTGRES_DB: music
  POSTGRES_USER: music
  POSTGRES_PASSWORD: musicpass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-db-primary-pvc
  namespace: yeahmusic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-db-primary
  namespace: yeahmusic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-db-primary
  template:
    metadata:
      labels:
        app: music-db-primary
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: music-db-credentials
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: music-db-primary-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: music-db-primary
  namespace: yeahmusic
spec:
  selector:
    app: music-db-primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-db-replica-pvc
  namespace: yeahmusic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-db-replica
  namespace: yeahmusic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-db-replica
  template:
    metadata:
      labels:
        app: music-db-replica
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: music-db-credentials
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: music-db-replica-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: music-db-replica
  namespace: yeahmusic
spec:
  selector:
    app: music-db-replica
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
