apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: yeahmusic
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    rule_files:
      - /etc/prometheus/rules.yml

    scrape_configs:
      - job_name: "api-gateway"
        static_configs:
          - targets: ["api-gateway:4010"]
        metrics_path: /metrics
      - job_name: "services"
        static_configs:
          - targets:
              - "auth-service:4001"
              - "music-service:4002"
              - "playlist-service:4003"
              - "upload-service:4004"
              - "analytics-service:4005"
              - "notification-service:4006"
        metrics_path: /metrics
  rules.yml: |
    groups:
      - name: yeahmusic-sre
        rules:
          - alert: ServiceDown
            expr: up == 0
            for: 30s
            labels:
              severity: critical
            annotations:
              summary: "Service is down"
              description: "Target {{ $labels.instance }} has been down for >30s."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: yeahmusic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.55.1
          args:
            - --config.file=/etc/prometheus/prometheus.yml
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
              - key: rules.yml
                path: rules.yml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: yeahmusic
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090

